name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # https://github.com/actions/checkout
      - name: Set up Node
        uses: actions/setup-node@v3 # https://github.com/actions/setup-node
        with:
          node-version-file: package.json
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
